const options = {
    jacket: {
      colors: {
        gray: "#545454",
        grayLight: "#8C8C8C",
        maroon: "#800A0A",
        maroonDark: "#5F2411",
        maroonDeep: "#3A0E12",
        blueLight: "#506C91",
        white: "#ffffff",
        navyBlue: "#071746",
        golden: "#C6985D",
      },
      buttons: {
        gray: "#545454",
        grayLight: "#8C8C8C",
        maroon: "#800A0A",
        maroonDark: "#5F2411",
        maroonDeep: "#3A0E12",
        blueLight: "#506C91",
        white: "#ffffff",
      },
      fabrics: {
        solid: "",
        pinstripe: "jacketpinstripe",
        chalkstripe: "jacketchalkstripe",
        windowpane: "jacketwindowpane",
        tattersall: "jackettattersall",
        herringbone: "jacketherringbone",
        barleycorn: "jacketbarleycorn",
        nailshead: "jacketnailshead",
        birdseye: "jacketbirdseye",
        glencheck: "jacketglencheck",
        shepherdscheck: "jacketshepherdscheck",
        tartan: "jackettartan",
        tartantwo: "jackettartantwo",
        houndstooth: "jackethoundstooth",
        paisley: "jacketpaisley",
        floral: "jacketfloral",
      },
    },
    shirt: {
      colors: {
        gray: "#545454",
        grayLight: "#8C8C8C",
        maroon: "#800A0A",
        maroonDark: "#5F2411",
        maroonDeep: "#3A0E12",
        blueLight: "#506C91",
        white: "#ffffff",
        navyBlue: "#071746",
        golden: "#C6985D",
      },
      buttons: {
        gray: "#545454",
        grayLight: "#8C8C8C",
        maroon: "#800A0A",
        maroonDark: "#5F2411",
        maroonDeep: "#3A0E12",
        blueLight: "#506C91",
        white: "#ffffff",
      },
      fabrics: {
        solid: "",
        pencilstripe: "shirtpencilstripe",
        stripe: "shirtstripe",
        awning: "shirtawning",
        gingham: "shirtgingham",
        graphcheck: "shirtgraphcheck",
        windowpane: "shirtwindowpane",
        tattersall: "shirttattersall",
        pindot: "shirtpindot",
        polkadot: "shirtpotkadot",
        tartan: "shirttartan",
        madras: "shirtmadras",
        paisley: "shirtpaisley",
        floral: "shirtfloral",
      },
    },
    tie: {
      colors: {
        gray: "#545454",
        grayLight: "#8C8C8C",
        maroon: "#800A0A",
        maroonDark: "#5F2411",
        maroonDeep: "#3A0E12",
        blueLight: "#506C91",
        white: "#ffffff",
        navyBlue: "#071746",
        golden: "#C6985D",
      },
      fabrics: {
        solid: "",
        pencilstripe: "tiepencilstripe",
        stripe: "tiestripe",
        awning: "tieawning",
        gingham: "tiegingham",
        graphcheck: "tiegraphcheck",
        windowpane: "tiewindowpane",
        tattersall: "tietattersall",
        pindot: "tiepindot",
        polkadot: "tiepotkadot",
        tartan: "tietartan",
        madras: "tiemadras",
        paisley: "tiepaisley",
        floral: "tiefloral",
      },
    },
    waistcoat: {
      colors: {
        gray: "#545454",
        grayLight: "#8C8C8C",
        maroon: "#800A0A",
        maroonDark: "#5F2411",
        maroonDeep: "#3A0E12",
        blueLight: "#506C91",
        white: "#ffffff",
        navyBlue: "#071746",
        golden: "#C6985D",
      },
      buttons: {
        gray: "#545454",
        grayLight: "#8C8C8C",
        maroon: "#800A0A",
        maroonDark: "#5F2411",
        maroonDeep: "#3A0E12",
        blueLight: "#506C91",
        white: "#ffffff",
      },
      fabrics: {
        solid: "",
        pinstripe: "waistcoatpinstripe",
        chalkstripe: "waistcoatchalkstripe",
        windowpane: "waistcoatwindowpane",
        tattersall: "waistcoattattersall",
        herringbone: "waistcoatherringbone",
        barleycorn: "waistcoatbarleycorn",
        nailshead: "waistcoatnailshead",
        birdseye: "waistcoatbirdseye",
        glencheck: "waistcoatglencheck",
        shepherdscheck: "waistcoatshepherdscheck",
        tartan: "waistcoattartan",
        tartantwo: "waistcoattartantwo",
        houndstooth: "waistcoathoundstooth",
        paisley: "waistcoatpaisley",
        floral: "waistcoatfloral",
      },
    },
    pants: {
      colors: {
        gray: "#545454",
        grayLight: "#8C8C8C",
        maroon: "#800A0A",
        maroonDark: "#5F2411",
        maroonDeep: "#3A0E12",
        blueLight: "#506C91",
        white: "#ffffff",
        navyBlue: "#071746",
        golden: "#C6985D",
      },
      buttons: {
        gray: "#545454",
        grayLight: "#8C8C8C",
        maroon: "#800A0A",
        maroonDark: "#5F2411",
        maroonDeep: "#3A0E12",
        blueLight: "#506C91",
        white: "#ffffff",
      },
      fabrics: {
        solid: "",
        pinstripe: "pantspinstripe",
        chalkstripe: "pantschalkstripe",
        windowpane: "pantswindowpane",
        tattersall: "pantstattersall",
        herringbone: "pantsherringbone",
        barleycorn: "pantsbarleycorn",
        nailshead: "pantsnailshead",
        birdseye: "pantsbirdseye",
        glencheck: "pantsglencheck",
        shepherdscheck: "pantsshepherdscheck",
        tartan: "pantstartan",
        tartantwo: "pantstartantwo",
        houndstooth: "pantshoundstooth",
        paisley: "pantspaisley",
        floral: "pantsfloral",
      },
    },
    shoe: {
      colors: {
        gray: "#545454",
        grayLight: "#8C8C8C",
        maroon: "#800A0A",
        maroonDark: "#5F2411",
        maroonDeep: "#3A0E12",
        blueLight: "#506C91",
        white: "#ffffff",
        navyBlue: "#071746",
        golden: "#C6985D",
      },
      strips: {
        gray: "#545454",
        grayLight: "#8C8C8C",
        maroon: "#800A0A",
        maroonDark: "#5F2411",
        maroonDeep: "#3A0E12",
        blueLight: "#506C91",
        white: "#ffffff",
      },
      sole: {
        gray: "#545454",
        grayLight: "#8C8C8C",
        maroon: "#800A0A",
        maroonDark: "#5F2411",
        maroonDeep: "#3A0E12",
        blueLight: "#506C91",
        white: "#ffffff",
      },
      pattern: {
        solid: "",
        suede: "shoeSuede",
        paisley: "shoePaisley",
        floral: "shoeFloral",
      },
    },
    beltPocket: {
      colors: {
        gray: "#545454",
        grayLight: "#8C8C8C",
        maroon: "#800A0A",
        maroonDark: "#5F2411",
        maroonDeep: "#3A0E12",
        blueLight: "#506C91",
        white: "#ffffff",
        navyBlue: "#071746",
        golden: "#C6985D",
      },
      pocketSquare: {
        gray: "#545454",
        grayLight: "#8C8C8C",
        maroon: "#800A0A",
        maroonDark: "#5F2411",
        maroonDeep: "#3A0E12",
        blueLight: "#506C91",
        white: "#ffffff",
      },
      socks: {
        gray: "#545454",
        grayLight: "#8C8C8C",
        maroon: "#800A0A",
        maroonDark: "#5F2411",
        maroonDeep: "#3A0E12",
        blueLight: "#506C91",
        white: "#ffffff",
      },
      buckle: {
        gray: "#545454",
        grayLight: "#8C8C8C",
        maroon: "#800A0A",
        maroonDark: "#5F2411",
        maroonDeep: "#3A0E12",
        blueLight: "#506C91",
        white: "#ffffff",
      }
    },
  };

  export {options}